name: CI

on:
  push:
    branches: [ "master", "ci" ]
    tags:
      - v?[0-9].[0-9]+.[0-9]+-[0-9]+
  pull_request:
    # The branches below must be a subset of the branches above
    branches: [ "master" ]

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        # os: [macos-latest, ubuntu-latest]
        os: [macos-latest]
    env:
      MACOSX_DEPLOYMENT_TARGET: 10.12
      RIMEV: 943b8c6

    steps:
    - uses: actions/checkout@v3
      with:
        submodules: recursive

    - name: Setup
      run: |
        brew install luajit
        brew install luarocks
        wget https://github.com/rime/librime/releases/download/latest/rime-$RIMEV-macOS.tar.bz2
        luarocks --lua-dir=/usr/local/opt/luajit install busted
        tar xjvf rime-$RIMEV-macOS.tar.bz2
        ln -s dist/lib
        git clone https://github.com/zhaozg/rime_simp.git var

    - name: Test
      run:
        ~/.luarocks/bin/busted
